---
- name: Kill project processes on all machines
  hosts: all
  become: true
  tasks:
    - name: Kill project processes on all machines
      command: killall -9 BFT-Distributed-G-Set-Remote
      become: true
      async: 1
      poll: 0
