---
- name: Kill project processes on all machines
  hosts: all
  become: true
  tasks:
    - name: Kill project processes on all machines
      command: killall -9 2-Atomic-Adds
      become: true
      async: 1
      poll: 0
