---
- name: Start scenario
  hosts: servers
  become: true
  tasks:
    - name: Fetch file hosts from node 0
      command: scp loukis@node0:/users/loukis/Thesis/BFT-Distributed-G-Set-V2/hosts /users/loukis/Thesis/BFT-Distributed-G-Set-V2/server
    - name: Start servers
      command: nohup /usr/local/go/bin/go run . > /dev/null &
      async: 3
      args:
        chdir: /users/loukis/Thesis/BFT-Distributed-G-Set-V2/server/
